[package]
name = "modern_compiler_implementation_in_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop = { version = "0.19.8", features = ["lexer"] }
lalrpop-util = "0.19.8"
regex = "1"