[package]
name = "modern_compiler_implementation_in_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = "0.14.0"
lalrpop = "*"
regex = "1"
